### ISSUE TITLE
Transpilation Problems with Getting Started

### ISSUE THREAD

**Issue by thomasAtToem** [cincheo/jsweet-examples#31]
Using the Getting Started Guide i get the followin g problems on latest Ubuntu.
java2ts seems to work (exisint target files) , ts2js not.
What can i change ?
thanks,
thomas

thomas@thomas:~/Desktop/jsweet/jsweet-quickstart$ mvn generate-sources
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.jsweet:jsweet-quickstart:jar:3.0.0-RC3
[WARNING] 'version' contains an expression but should be a constant. @ org.jsweet:jsweet-quickstart:${jsweet.transpiler.version}, /home/thomas/Schreibtisch/jsweet/jsweet-quickstart/pom.xml, line 6, column 11
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] --------------------< org.jsweet:jsweet-quickstart >--------------------
[INFO] Building JSweet quick start 3.0.0-RC3
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- jsweet-maven-plugin:3.0.0-RC3:jsweet (generate-js) @ jsweet-quickstart ---
[INFO] maven version: 3.6.3
[INFO] JSweet transpiler version 3.0.0-RC3 (build date: 2020-05-18 18:28:16)
[INFO] dependencies=[Dependency {groupId=org.jsweet, artifactId=jsweet-core, version=6.2.0, type=jar}, Dependency {groupId=org.jsweet.candies, artifactId=jquery, version=1.10.0-20170726, type=jar}]
[INFO] candies detection: add project dependency Dependency {groupId=org.jsweet, artifactId=jsweet-core, version=6.2.0, type=jar} => org.jsweet:jsweet-core:jar:6.2.0:compile
[INFO] candies detection: add project dependency Dependency {groupId=org.jsweet.candies, artifactId=jquery, version=1.10.0-20170726, type=jar} => org.jsweet.candies:jquery:jar:1.10.0-20170726:compile
[INFO] all candies artifacts: [org.jsweet:jsweet-core:jar:6.2.0:compile (1; enabled), org.jsweet.candies:jquery:jar:1.10.0-20170726:compile (1; enabled)]
[INFO] candies jars: [/home/thomas/.m2/repository/org/jsweet/jsweet-core/6.2.0/jsweet-core-6.2.0.jar, /home/thomas/.m2/repository/org/jsweet/candies/jquery/1.10.0-20170726/jquery-1.10.0-20170726.jar]
[INFO] classpath from maven: /home/thomas/.m2/repository/org/jsweet/jsweet-core/6.2.0/jsweet-core-6.2.0.jar:/home/thomas/.m2/repository/org/jsweet/candies/jquery/1.10.0-20170726/jquery-1.10.0-20170726.jar
[INFO] jsOut: /home/thomas/Schreibtisch/jsweet/jsweet-quickstart/target/js
[INFO] bundle: null
[INFO] tsOut: /home/thomas/Schreibtisch/jsweet/jsweet-quickstart/target/ts
[INFO] tsOnly: null
[INFO] tsserver: null
[INFO] declarations: null
[INFO] ignoreDefinitions: null
[INFO] declarationOutDir: null
[INFO] candiesJsOutDir: /home/thomas/Schreibtisch/jsweet/jsweet-quickstart/webapp/candies
[INFO] ecmaTargetVersion: ES6
[INFO] moduleKind: none
[INFO] sourceMap: null
[INFO] sourceRoot: null
[INFO] verbose: true
[INFO] veryVerbose: null
[INFO] jdkHome: /usr/lib/jvm/java-11-openjdk-amd64
[INFO] factoryClassName: null
[INFO] ignoredProblems: null
[INFO] extraSystemPath: null
2020-07-02 08:59:45.045 INFO  JSweetTranspiler:389 - no configuration file found at /home/thomas/Schreibtisch/jsweet/jsweet-quickstart/jsweetconfig.json
2020-07-02 08:59:45.045 INFO  JSweetTranspiler:494 - creating transpiler version 3.0.0-RC3 (build date: 2020-05-18 18:28:16)
2020-07-02 08:59:45.045 INFO  JSweetTranspiler:496 - current dir: /home/thomas/Schreibtisch/jsweet/jsweet-quickstart/.
2020-07-02 08:59:45.045 INFO  JSweetTranspiler:497 - base directory: /home/thomas/Schreibtisch/jsweet/jsweet-quickstart
2020-07-02 08:59:45.045 INFO  JSweetTranspiler:498 - working directory: /home/thomas/Schreibtisch/jsweet/jsweet-quickstart/.jsweet
2020-07-02 08:59:45.045 INFO  JSweetTranspiler:499 - tsOut: /home/thomas/Schreibtisch/jsweet/jsweet-quickstart/target/ts - /home/thomas/Schreibtisch/jsweet/jsweet-quickstart/target/ts
2020-07-02 08:59:45.045 INFO  JSweetTranspiler:500 - jsOut: /home/thomas/Schreibtisch/jsweet/jsweet-quickstart/target/js - /home/thomas/Schreibtisch/jsweet/jsweet-quickstart/target/js
2020-07-02 08:59:45.045 INFO  JSweetTranspiler:501 - candyJsOut: /home/thomas/Schreibtisch/jsweet/jsweet-quickstart/webapp/candies
2020-07-02 08:59:45.045 INFO  JSweetTranspiler:502 - factory: org.jsweet.transpiler.JSweetFactory@7e1f584d
2020-07-02 08:59:45.045 DEBUG JSweetTranspiler:503 - compile classpath: /home/thomas/Schreibtisch/jsweet/jsweet-quickstart/jsweet_extension:/home/thomas/.m2/repository/org/jsweet/jsweet-core/6.2.0/jsweet-core-6.2.0.jar:/home/thomas/.m2/repository/org/jsweet/candies/jquery/1.10.0-20170726/jquery-1.10.0-20170726.jar
2020-07-02 08:59:45.045 DEBUG JSweetTranspiler:504 - runtime classpath: /usr/share/maven/boot/plexus-classworlds-2.x.jar
2020-07-02 08:59:45.045 DEBUG JSweetTranspiler:505 - extension directory: /home/thomas/Schreibtisch/jsweet/jsweet-quickstart/jsweet_extension
2020-07-02 08:59:45.045 INFO  CandyProcessor:123 - candies processor classpath: /home/thomas/Schreibtisch/jsweet/jsweet-quickstart/jsweet_extension:/home/thomas/.m2/repository/org/jsweet/jsweet-core/6.2.0/jsweet-core-6.2.0.jar:/home/thomas/.m2/repository/org/jsweet/candies/jquery/1.10.0-20170726/jquery-1.10.0-20170726.jar
2020-07-02 08:59:45.045 INFO  CandyProcessor:141 - extracted candies directory: /home/thomas/Schreibtisch/jsweet/jsweet-quickstart/webapp/candies
[INFO] source includes: {}
[INFO] source excludes: {}
[INFO] sources paths: [/home/thomas/Schreibtisch/jsweet/jsweet-quickstart/src/main/java]
[INFO] sources paths from resources: [/home/thomas/Schreibtisch/jsweet/jsweet-quickstart/src/main/java]
[INFO] sourceFiles=[/home/thomas/Schreibtisch/jsweet/jsweet-quickstart/src/main/java/quickstart/QuickStart.java]
2020-07-02 08:59:45.045 DEBUG ProcessUtil:66 - extra path: 
2020-07-02 08:59:45.045 INFO  ProcessUtil:126 - cannot find tsc - searching in node_modules files
2020-07-02 08:59:45.045 INFO  ProcessUtil:126 - cannot find tsc - searching in node_modules files
2020-07-02 08:59:45.045 DEBUG ProcessUtil:369 - installing typescript with npm
2020-07-02 08:59:45.045 DEBUG ProcessUtil:66 - extra path: 
2020-07-02 08:59:45.045 DEBUG ProcessUtil:288 - run command: /bin/sh -c npm install --prefix /home/thomas/.jsweet-node_modules typescript@3.7.4
2020-07-02 08:59:45.045 DEBUG ProcessUtil:303 - started [/bin/sh, -c, npm install --prefix /home/thomas/.jsweet-node_modules typescript@3.7.4]
2020-07-02 08:59:45.045 INFO  ProcessUtil:320 - npm - /bin/sh: 1: npm: not found
2020-07-02 08:59:45.045 INFO  CandyProcessor:226 - 2 candies found in classpath
2020-07-02 08:59:45.045 INFO  CandyProcessor:163 - candies are up to date
2020-07-02 08:59:45.045 DEBUG JavaCompilationComponents:102 - charset: UTF-8
2020-07-02 08:59:45.045 DEBUG JavaCompilationComponents:103 - strict mode: false
2020-07-02 08:59:45.045 INFO  JavaCompilationComponents:114 - creating JavaCompiler task with options: JavaCompilerOptions: [--module-path, /home/thomas/Schreibtisch/jsweet/jsweet-quickstart/jsweet_extension:/home/thomas/.m2/repository/org/jsweet/jsweet-core/6.2.0/jsweet-core-6.2.0.jar:/home/thomas/.m2/repository/org/jsweet/candies/jquery/1.10.0-20170726/jquery-1.10.0-20170726.jar, -cp, /home/thomas/Schreibtisch/jsweet/jsweet-quickstart/jsweet_extension:/home/thomas/.m2/repository/org/jsweet/jsweet-core/6.2.0/jsweet-core-6.2.0.jar:/home/thomas/.m2/repository/org/jsweet/candies/jquery/1.10.0-20170726/jquery-1.10.0-20170726.jar, -Xlint:path, -encoding, UTF-8]
2020-07-02 08:59:45.045 INFO  JSweetTranspiler:877 - scanning /home/thomas/Schreibtisch/jsweet/jsweet-quickstart/src/main/java/quickstart/QuickStart.java...
2020-07-02 08:59:45.045 INFO  JSweetTranspiler:903 - output file: quickstart/QuickStart.ts
2020-07-02 08:59:45.045 INFO  JSweetTranspiler:928 - created /home/thomas/Schreibtisch/jsweet/jsweet-quickstart/target/ts/quickstart/QuickStart.ts
2020-07-02 08:59:45.045 INFO  JSweetTranspiler:800 - ts2js on org.jsweet.transpiler.TypeScript2JavaScriptWithTscTranspiler@303c55fa sourceFiles=1
2020-07-02 08:59:45.045 DEBUG TypeScript2JavaScriptWithTscTranspiler:33 - ts2js with TSC: [/home/thomas/Schreibtisch/jsweet/jsweet-quickstart/target/ts/quickstart/QuickStart.ts, /home/thomas/Schreibtisch/jsweet/jsweet-quickstart/.jsweet/candies/typings/META-INF/resources/typings/jquery/1.10.0-20170726/bundle.d.ts]
2020-07-02 08:59:45.045 INFO  TypeScript2JavaScriptWithTscTranspiler:80 - launching tsc...
2020-07-02 08:59:45.045 INFO  ProcessUtil:126 - cannot find tsc - searching in node_modules files
2020-07-02 08:59:45.045 DEBUG ProcessUtil:288 - run command:  --target ES6 --moduleResolution classic --experimentalDecorators --emitDecoratorMetadata --rootDir /home/thomas/Schreibtisch/jsweet/jsweet-quickstart/target/ts --outDir /home/thomas/Schreibtisch/jsweet/jsweet-quickstart/target/js .tsc-rootfile.ts quickstart/QuickStart.ts ../../.jsweet/candies/typings/META-INF/resources/typings/jquery/1.10.0-20170726/bundle.d.ts
2020-07-02 08:59:45.045 ERROR ProcessUtil:349 - 
java.lang.NullPointerException
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1090)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at org.jsweet.transpiler.util.ProcessUtil.runCommand(ProcessUtil.java:301)
	at org.jsweet.transpiler.TypeScript2JavaScriptWithTscTranspiler.doTranspile(TypeScript2JavaScriptWithTscTranspiler.java:88)
	at org.jsweet.transpiler.TypeScript2JavaScriptTranspiler.ts2js(TypeScript2JavaScriptTranspiler.java:36)
	at org.jsweet.transpiler.JSweetTranspiler.ts2js(JSweetTranspiler.java:801)
	at org.jsweet.transpiler.JSweetTranspiler.transpile(JSweetTranspiler.java:776)
	at org.jsweet.AbstractJSweetMojo.transpile(AbstractJSweetMojo.java:606)
	at org.jsweet.JSweetMojo.execute(JSweetMojo.java:43)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
2020-07-02 08:59:45.045 ERROR output:55 - Unknown tsc error
2020-07-02 08:59:45.045 INFO  JSweetTranspiler:784 - transpilation process finished in 852 ms 
> java2ts: 695.55967ms
> ts2js: 17.130283ms

[ERROR] transpilation failed
org.apache.maven.plugin.MojoFailureException: transpilation failed with 1 error(s) and 0 warning(s)
    at org.jsweet.AbstractJSweetMojo.transpile (AbstractJSweetMojo.java:618)
    at org.jsweet.JSweetMojo.execute (JSweetMojo.java:43)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.562 s
[INFO] Finished at: 2020-07-02T08:59:45+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jsweet:jsweet-maven-plugin:3.0.0-RC3:jsweet (generate-js) on project jsweet-quickstart: transpilation failed: transpilation failed with 1 error(s) and 0 warning(s) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by lgrignon** [comment]
Hello, thanks for reporting. Which version of java / maven / JSweet are you using please?

**Comment by thomasAtToem** [comment]
Hi, sorry for letting it open. It was an environment problem that was solved. Thanks !!!
